
TYPE
	FormatStringArguments_typ : 	STRUCT 
		r : ARRAY[0..MAX_INDEX_FORMAT_STR_ARGS]OF REAL;
		i : ARRAY[0..MAX_INDEX_FORMAT_STR_ARGS]OF INT;
		s : ARRAY[0..MAX_INDEX_FORMAT_STR_ARGS]OF STRING[STR_LEN_FORMAT_STR_ARGS];
	END_STRUCT;
END_TYPE
